apiVersion: v2
name: kpow
description: Run Kpow for Apache Kafka in Kubernetes
type: application
version: 1.0.55
appVersion: "94.1"
keywords:
  - kafka
  - kafka-ui
  - kafka-connect
  - schema-registry
  - monitoring
home: "https://factorhouse.io/kpow"
sources:
  - "https://github.com/factorhouse/kpow"
  - "https://github.com/factorhouse/kpow-helm-charts-lm/"
maintainers:
  - name: "Factor House Support"
    email: "support@factorhouse.io"
